# Inactive
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: tools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: cloudflared
    targetRevision: 2.0.9
    helm:
      values: |
        tunnelSecrets:
          base64EncodedPemFile: ""
          base64EncodedConfigJsonFile: ""
        tunnelConfig:
          name: "k8s-tunnel"
        ingress:
            - hostname: 'argocd.ictbit-labs.com'
              service: "http://argocd-server.argocd.svc.cluster.local:80"
            - service: http_status:404
        resources:
          requests:
            cpu: 10m
            memory: 25Mi           