apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: tools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.18.0
    chart: external-secrets
    helm:
      values: |
        serviceAccount:
          name: external-secrets
          annotations:
            iam.gke.io/gcp-service-account: gke-apps@uri-labs-465111.iam.gserviceaccount.com
        extraObjects:
        -
          apiVersion: external-secrets.io/v1
          kind: ClusterSecretStore
          metadata:
            name: gcp-secret-store
            namespace: tools
          spec:
            provider:
              gcpsm:
                projectID: uri-labs-465111