name: Terraform - GCP

on:
  push:
    branches:
      - master
    paths:
      - gcp/terraform/**
  workflow_dispatch:
    inputs:
      working_directory:
        required: true
        description: 'Enter your working directory'
        type: string
        default: 'gcp/terraform'
      apply:
        type: boolean
        description: 'Run Terraform Apply?'
        required: true
        default: false
      destroy:
        type: boolean
        description: 'Run Terraform Destroy?'
        required: true
        default: false

permissions:
  id-token: write
  contents: read
env:
  terraform_version: 1.12.0
  WIP: "projects/000000000/locations/global/workloadIdentityPools/cicd/providers/github"
  PROJECT_ID: "00000"
  SA: "cicd-sa@00000.iam.gserviceaccount.com"

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || ( github.event_name == 'workflow_dispatch' && github.event.inputs.apply != 'true' && github.event.inputs.destroy != 'true')
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working_directory || 'gcp/terraform' }}
    steps:
      - uses: actions/checkout@v2
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WIP }}
          service_account: ${{ env.SA }}
          project_id: ${{ env.PROJECT_ID }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{env.terraform_version}}
      - name: Terraform init
        id: init
        run: terraform init
      - name: Terraform plan
        id: plan
        run: terraform plan -no-color -input=false
  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && inputs.apply == true
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working_directory }}
    steps:
      - uses: actions/checkout@v2
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WIP }}
          service_account: ${{ env.SA }}
          project_id: ${{ env.PROJECT_ID }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{env.terraform_version}}
      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform apply
        id: apply
        run: terraform apply -auto-approve -no-color -input=false

  destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && inputs.destroy == true
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working_directory }}
    steps:
      - uses: actions/checkout@v2
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WIP }}
          service_account: ${{ env.SA }}
          project_id: ${{ env.PROJECT_ID }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{env.terraform_version}}
      - name: Terraform init
        id: init
        run: terraform init

      - name: Terraform destroy
        id: destroy
        run: terraform destroy -auto-approve